// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StatisticService.Infrastructure.Data;

#nullable disable

namespace StatisticService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("StatisticService.Domain.Entities.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Statistics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlayCount = 3131,
                            TrackId = 3
                        },
                        new
                        {
                            Id = 2,
                            PlayCount = 33123,
                            TrackId = 33
                        },
                        new
                        {
                            Id = 3,
                            PlayCount = 10931,
                            TrackId = 49
                        },
                        new
                        {
                            Id = 4,
                            PlayCount = 5543,
                            TrackId = 76
                        },
                        new
                        {
                            Id = 5,
                            PlayCount = 122,
                            TrackId = 102
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
