// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StatisticService.Infrastructure.Data;

#nullable disable

namespace StatisticService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("StatisticService.Domain.Entities.Statistic", b =>
                {
                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrackId", "PlayCount");

                    b.ToTable("Statistics");

                    b.HasData(
                        new
                        {
                            TrackId = 3,
                            PlayCount = 3131
                        },
                        new
                        {
                            TrackId = 33,
                            PlayCount = 33123
                        },
                        new
                        {
                            TrackId = 49,
                            PlayCount = 10931
                        },
                        new
                        {
                            TrackId = 76,
                            PlayCount = 5543
                        },
                        new
                        {
                            TrackId = 102,
                            PlayCount = 122
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
