// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackService.Infrastructure.Data;

#nullable disable

namespace TrackService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TrackService.Domain.Entities.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "---",
                            Name = "Cole Will"
                        });
                });

            modelBuilder.Entity("TrackService.Domain.Entities.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 33,
                            ArtistId = 1,
                            Description = "---",
                            Title = "Not You"
                        },
                        new
                        {
                            Id = 49,
                            ArtistId = 1,
                            Description = "---",
                            Title = "Legendary"
                        },
                        new
                        {
                            Id = 76,
                            ArtistId = 1,
                            Description = "---",
                            Title = "Мои клиенты"
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 1,
                            Description = "---",
                            Title = "Holding On"
                        },
                        new
                        {
                            Id = 102,
                            ArtistId = 1,
                            Description = "---",
                            Title = "Poppin"
                        });
                });

            modelBuilder.Entity("TrackService.Domain.Entities.Track", b =>
                {
                    b.HasOne("TrackService.Domain.Entities.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("TrackService.Domain.Entities.Artist", b =>
                {
                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
